port=12220
server="localhost"
echo "GET"
curl -X GET "http://spider.foi.hr:12228/api/korisnici/"
echo ""
echo "POST"
curl -X POST "http://spider.foi.hr:12228/api/korisnici/" -H "Content-Type: application/json" -d "{\"korime\":\"Test\", \"lozinka\":\"123456\", \"email\":\"test3@foi.unizg.hr\", \"ime\":\"test\", \"prezime\":\"test\", \"adresa\":\"test\"}" 
echo ""
echo "DELETE"
curl -X DELETE "http://$server:$port/api/korisnici/"
echo ""
echo "PUT"
curl -X PUT "http://$server:$port/api/korisnici/"
echo ""
echo "GET"
curl -X GET "http://spider.foi.hr:12228/api/korisnici/pkos"
echo ""
echo "GET prijava tocna"
curl -X POST "http://$server:$port/api/korisnici/pkos/prijava" -H 'Content-Type: application/json' -d '{"lozinka":"123456"}'
echo ""
echo "GET prijava kriva"
curl -X POST "http://spider.foi.hr:12228/api/korisnici/lkralj/prijava" -H 'Content-Type: application/json' -d '{"lozinka":"kralj"}'
echo ""
echo "PUT"
curl -X PUT "http://spider.foi.hr:12228/api/korisnici/lkralj" -H 'Content-Type: application/json' -d '{"ime":"Test2", "prezime":"Test", "lozinka":"123456", "email":"test2@foi.unizg.hr"}'
echo ""
echo "DELETE"
curl -X DELETE "http://$server:$port/api/korisnici/test"
echo ""
echo "POST"
curl -X POST "http://$server:$port/api/korisnici/test"
echo ""